version: 1.2.{build}

image: Visual Studio 2017

before_build:
- cmd: nuget restore Renci.SshNet.Async.sln

build:
  project: Renci.SshNet.Async.sln

artifacts:
  - path: '**\*.nupkg'

environment:
  my_variable:
    

deploy:
  provider: NuGet
  api_key:
    secure: pz0I0jyd5/oGyB+1uOHl+Q+YA/5v4lRMOnUs4Xrx/8k2AWwxuTdkmU2mlYvWxSQp
  artifact: /.*\.nupkg/
  on:
      appveyor_repo_tag: true